spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/hip_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
    register-with-eureka: true
    fetch-registry: true


