spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policy/**
          filters:
            - AuthFilter
server:
  port: 9090
eureka:
  client:
    instance:
      hostname: localhost
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
