spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: harshadeveloper.999@gmail.com
    password: aiyskmpbwonqrvlg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
    register-with-eureka: true
    fetch-registry: true