spring:
  application:
    name: user-service-dev
  datasource:
    url: jdbc:mysql://localhost:3306/hip_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080


