spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harsha2nani/Insurance_Policy_MSV
          default-label: main
          search-paths:
            - Insurance-Config
            - Insurance-Config/Environments
            - Insurance-user-service/user-service
            - Insurance-user-service/user-service/Environments

server:
  port: 9095

